version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./piggy:/app/piggy
      - ./processed_senators.json:/app/processed_senators.json
    environment:
      - PORT=8000
